spring:
  application:
    name: AiLock

  ai:
    ollama:
      base-url: http://168.188.128.36:20251

      chat:
        model: gemma3:12b

      embedding:
        options:
          model: bge-m3

  datasource:
    url: jdbc:postgresql://localhost:15432/remind
    username: postgres
    password: "0514"
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 16379

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080